server:
  port: 8082
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /profile-management-service/v3/api-docs
  swagger-ui:
    path: /profile-management-service/swagger-ui.html

openapi:  # This should be nested under the springdoc section
  service:
    title: profile-management-service doc
    version: 1.0.0
    url: http://localhost:8777

spring:
  application:
    name: PROFILE-MANAGEMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/DMS
    username: root
    password: impetus
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka


my:
  password: Shivam@123
